CREATE TABLE `hotelinfo` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`hotelName` VARCHAR(50) NULL DEFAULT NULL COMMENT '酒店名',
	`hotelAddress` VARCHAR(50) NULL DEFAULT NULL COMMENT '酒店地址',
	`phone` VARCHAR(50) NULL DEFAULT NULL COMMENT '酒店联系电话',
	`facility` VARCHAR(50) NULL DEFAULT NULL COMMENT '设施',
	`hotelText` VARCHAR(300) NULL DEFAULT NULL COMMENT '酒店介绍',
	PRIMARY KEY (`id`)
)
COMMENT='酒店信息表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB