CREATE TABLE `user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `openid` VARCHAR(255) NULL DEFAULT NULL,
  `sessionkey` VARCHAR(255) NULL DEFAULT NULL,
  `level` INT(11) NULL DEFAULT '0',
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `nickname` VARCHAR(50) NULL DEFAULT NULL,
  `gender` INT(11) NULL DEFAULT NULL,
  `avatarurl` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户表';
